comm_text = {'mb_text_1': 'Input device IP: ',
             'mb_error_1': 'You did input wrong IP! Please input correct data: ',
             'mb_text_2': 'Input TCP-port: ',
             'mb_error_2': 'You did input wrong TCP-port! Please input correct data: ',
             'mb_text_3': 'Input register address: ',
             'mb_error_3': 'You did input wrong register address! Please input correct data: ',
             'mb_text_4': 'Input quantity of registers: ',
             'mb_error_4': 'You did input wrong quantity of registers! Please input correct data: ',
             'mb_text_5': 'Input registers type (1=COILS 2= DISCRETE INPUTS 3=HOLDING REGISTERS 4=INPUT REGISTERS: ',
             'mb_error_5': 'You did input wrong registers type! Please input correct data: ',
             'scan_text_1': 'Input start IP-address: ',
             'scan_error_1': 'You did input wrong IP-address! Please input correct data: ',
             'scan_text_2': 'Input quantity of IP-addresses(1-255): ',
             'scan_error_2': 'You did input wrong quantity of IP-addresses! Please input correct data: ',
             'bn_text_1': 'Input IP-address of using host interface: ',
             'bn_error_1': 'You did input wrong IP-address! Please input correct data: ',
             'bn_text_2': 'Input device IP-address: ',
             'bn_error_2': 'You did input wrong IP-address! Please input correct data: ',
             'bn_text_3': 'Input listening UDP-port: ',
             'bn_error_3': 'You did input wrong UDP-port! Please input correct data: ',
             'bn_text_4': 'Input object ID: ',
             'bn_error_4': 'You did input wrong ID! Please input correct data: ',
             'bn_text_5': 'Choose ACTION (1= SEND WHO-IS, 2=GET OBJECT LIST, 3=READ OBJECT PROPERTY): ',
             'bn_error_5': 'You did input wrong ACTION! Please input correct data: ',
             'bn_text_6': 'Input OBJECT TYPE (0=AI, 1=AO, 2=AV, 3=BI, 4=BO,5=BV, 13=MSI, 14=MSO, 19=MSV): ',
             'bn_error_6': 'You did input wrong OBJECT TYPE! Please input correct data: '
             }
